### ISSUE TITLE
mount log path

### ISSUE THREAD

**Issue by lincoln310** [edenb/docker-thingsboard-gateway#1]
Hi, i want to mount an extern path for log, where is the default path of the log?

**Comment by lincoln310** [comment]
and where to put the conf ?

**Comment by edenb** [comment]
When you use the provided docker-compose file the log and config dir are already mounted to /data/..... on the host.

**Comment by lincoln310** [comment]
I create a new docker-compose.yml to use your images:

version: '2'
services:
  thingsboard-gateway:
    image: "edenb/thingsboard-gateway"
    restart: always
    expose:
      - '9090'
    volumes:
      - ./conf:/etc/tb-gateway/conf
      - ./log:/var/log/tb-gateway

but no output to the log.

**Comment by edenb** [comment]
[This is not how it works.](https://stackoverflow.com/questions/42395748/docker-compose-volume-is-empty-even-from-initialize) I fixed it by mounting a named volume to a directory on the host. You should first create `/data/log` and `/data/conf` before running docker-compose otherwise the mount will fail on creation of the container.

```
version: '2'
services:
  thingsboard-gateway:
    image: 'edenb/thingsboard-gateway'
    restart: always
    expose:
      - '9090'
    volumes:
      - thingsboard-gateway-conf-data:/etc/tb-gateway/conf
      - thingsboard-gateway-log-data:/var/log/tb-gateway
volumes:
  thingsboard-gateway-conf-data:
    driver: local
    driver_opts:
      type: none
      device: /data/conf
      o: bind
  thingsboard-gateway-log-data:
    driver: local
    driver_opts:
      type: none
      device: /data/log
      o: bind

```
