### ISSUE TITLE
mqtt host config error

### ISSUE THREAD

**Issue by lincoln310** [edenb/docker-thingsboard-gateway#2]
I use docker logs to get the log, and it showed a "localhost:1883" connection failed, but i did't set this connection.

this is the tb-gateway.yml:
```
gateways:
  tenants:
    -
      label: "default tenant"
      reporting:
        interval: 60000
      persistence:
        type: file
        path: storage
        bufferSize: 1000
      connection:
        host: "${THINGSBOARD_HOST}"
        port: 1883
        retryInterval: 3000
        maxInFlight: 1000
        security:
          accessToken: "${ACCESS_TOKEN}"
      remoteConfiguration: false
      extensions:
        -
          id: "mqtt1"
          type: "MQTT"
          extensionConfiguration: "${MQTT_CONFIG:mqtt-config.json}"
```
and this is the mqtt-config.json:
```
{
  "brokers": [
    {
      "host": "${MOSQUITTO_HOST}",
      "port": ${MOSQUITTO_PORT},
      "ssl": false,
      "retryInterval": 3000,
      "credentials": {
        "type": "anonymous"
      },
      "mapping": [
        {
          "topicFilter": "sensors",
          "converter": {
            "type": "json",
            "filterExpression": "",
            "deviceNameJsonExpression": "${$.serialNumber}",
            "timeout": 60000,
            "attributes": [
              {
                "type": "string",
                "key": "model",
                "value": "${$.model}"
              }
            ],
            "timeseries": [
              {
                "type": "double",
                "key": "temperature",
                "value": "${$.temperature}"
              }
            ]
          }
        }
      ]
    }
  ]
}
```
